### ISSUE TITLE
Review cache busting

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#270]
Deployment to CU did not appear to be correctly cache busting, based on the fact that it did not display the Show More link.

We need to decide:

- [ ] grooming: is this a big enough concern to spend time on?
- [ ] is there a cache busting issue we should be seriously looking into?

**Comment by mcquinne** [comment]
Updates:
1. We were, indeed, not using hashes in output files names to bust caching
1. I personally found this frustrating since we definitely were doing it before
1. I updated the prod webpack config to restore the hashing in output files names
1. The fix is applied to both the master and release/1.x branches via the two commits above
1. I believe this is resolved now

**Comment by zebdelk** [comment]
Based on doing the 1.3 release checklist, I suspect we're still not busting the cache for css files. I'm not familiar enough with webpack to confirm for sure, but I wrote up #344 to revisit that aspect.
